### ISSUE TITLE
Add support for l4t 36.x

### ISSUE THREAD

**Issue by pythops** [pythops/jetson-image#108]

**Comment by raj-khare** [comment]
any updates on this? really need this

**Comment by pythops** [comment]
I might have something by the end of this week yes

**Comment by raj-khare** [comment]
also if possible, pls add support to flash the image to nvme drive

**Comment by pythops** [comment]
Sure

**Comment by BBO-TheyeQ** [comment]
Hello, is it still an ongoing task ?

**Comment by pythops** [comment]
yes, there is a draft PR for it

**Comment by pythops** [comment]
Fixed
