### ISSUE TITLE
Add support for agx orin board

### ISSUE THREAD

**Issue by pythops** [pythops/jetson-image#113]

**Comment by raj-khare** [comment]
hey any update on this?

**Comment by raj-khare** [comment]
nvidia's create_sample_fs script is really trash

**Comment by pythops** [comment]
not yet. 
I'm working on l4t 36.x and then i'll take a look at agx orin

**Comment by pythops** [comment]
I can fix it. @richyo-work will you be able to test plz :pray: ?
