### ISSUE TITLE
No internet access through domain names

### ISSUE THREAD

**Issue by jasonlytehouse** [pythops/jetson-image#123]
When using the latest Jetson Nano 20.04 prebuilt images I was not able to access internet using domain name resolution.

`ping 8.8.8.8` resolved
`ping www.google.com` failed

Fix:
- Add a custom systemd-resolved config:
```shell
sudo vi /etc/systemd/resolved.conf.d/custom.conf
```
- Press `i` and paste this:
```vi
[Resolve]
DNS=8.8.8.8 8.8.4.4
```
Then save and quit using `Esc` then `:wq`
- Link the /etc/resolv.conf to point to systemd-resolver config
```shell
rm -f /etc/resolv.conf
ln -sv /run/systemd/resolve/resolv.conf /etc/resolv.conf
```
- Restart the network resolver using
```shell
systemctl restart systemd-resolved
```
- Verify it's working by running
```shell
ping www.google.com
```

**Comment by pythops** [comment]
it is fixed in the main branch but the new images are not built yet. so if you build an image yourself you should not have the issue anymore
